# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# no PR builds
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: Bash@3
  displayName: 'Configure variables'
  inputs:
    filePath: '.azure/workflows/configure-variables-release.sh'
    failOnStderr: true

# Install .NET Core SDK
- task: UseDotNet@2
  displayName: 'Install Net Core 2.2'
  inputs:
    version: '2.2.x'
- task: UseDotNet@2
  displayName: 'Install Net Core 3.1'
  inputs:
    version: '3.1.x'

# SonarCloud Prepare Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Daniel127'
    organization: 'daniel127'
    scannerMode: 'MSBuild'
    projectKey: 'ef-unit-of-work'
    projectName: 'EF-Unit-Of-Work'

# Build solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

# Test solution
- task: DotNetCoreCLI@2
  displayName: 'Execute tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code Coverage"'

# SonarCloud analyze and publish results
- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Create Nuget package'
  inputs:
    command: 'pack'
    packagesToPack: '**/QD.EntityFrameworkCore.UnitOfWork.csproj'
    configuration: '$(buildConfiguration)'
    packDirectory: '$(Pipeline.Workspace)/nuget'
    nobuild: true
    versioningScheme: 'off'

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)/nuget'
    artifact: 'Package'